In [2]:
import requests
import pandas as pd
import time

In [3]:
df = pd.read_csv("../data/movies_1990_2026.csv")

In [8]:
df.sample(10)

,id,title,year,description,genres,rating,num_votes,adult
1446,6498,Nightwatch,1994,"Martin, a law student, takes up a job as a nig...","['Horror', 'Thriller']",6.908,316,False
9073,623491,The Babysitter: Killer Queen,2020,Two years after defeating a satanic cult led b...,"['Comedy', 'Horror']",6.323,1829,False
5454,12289,Red Cliff,2008,"In 208 A.D., in the final days of the Han Dyna...","['Adventure', 'Drama', 'History', 'Action', 'W...",7.100,884,False
8640,505058,Unfriended: Dark Web,2018,​When a 20-something finds a cache of hidden f...,"['Horror', 'Mystery']",6.282,1660,False
3526,28308,The Body,2001,An ancient skeleton has been discovered in Jer...,"['Drama', 'Mystery', 'Romance', 'Thriller']",5.530,231,False
10955,1630433,The Red Line,2026,Three women fall prey to a ruthless phone scam...,"['Thriller', 'Crime', 'Drama']",6.900,52,False
5718,22832,Ninja Assassin,2009,"Ninja Assassin follows Raizo, one of the deadl...","['Action', 'Adventure', 'Thriller']",6.672,1754,False
9830,667739,The Man from Toronto,2022,A case of mistaken identity forces a bumbling ...,"['Action', 'Adventure', 'Comedy']",6.382,508,False
8771,696026,Nice Sister-In-Law,2019,"Young-cheol, faced with boredom, keeps looking...","['Drama', 'Romance']",8.000,2,False
10445,1353436,KA,2024,"Set in 1970s Abhinaya Vasudev, an orphaned and...","['Action', 'Thriller']",6.500,6,False

In [4]:
df.shape

(11100, 8)

In [6]:
df.describe()

                 id          year        rating     num_votes
count  1.110000e+04  11100.000000  11100.000000  11100.000000
mean   2.924136e+05   2008.000000      6.340943   1613.943423
std    3.860630e+05     10.677559      1.287056   3230.858620
min    5.000000e+00   1990.000000      0.000000      0.000000
25%    1.373975e+04   1999.000000      5.900000     66.000000
50%    8.027250e+04   2008.000000      6.500000    429.000000
75%    4.581012e+05   2017.000000      7.072250   1635.000000
max    1.691404e+06   2026.000000     10.000000  39623.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11100 entries, 0 to 11099
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           11100 non-null  int64
 1   title        11100 non-null  object
 2   year         11100 non-null  int64
 3   description  11038 non-null  object
 4   genres       11100 non-null  object
 5   rating       11100 non-null  float64
 6   num_votes    11100 non-null  int64
 7   adult        11100 non-null  bool
dtypes: bool(1), float64(1), int64(3), object(3)
memory usage: 618.0+ KB